//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Products
    {
        public int ID_Info_Products { get; set; }
        public int Info_Orders_ID { get; set; }
        public int Product_ID { get; set; }
    
        public virtual Info_Orders Info_Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
