//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Info_Orders()
        {
            this.Info_Products = new HashSet<Info_Products>();
        }
    
        public int ID_Info_Orders { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Payment { get; set; }
        public int User_ID { get; set; }
        public decimal Change { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Info_Products> Info_Products { get; set; }
    }
}
