//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinyl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Info_Products = new HashSet<Info_Products>();
        }
    
        public int ID_Products { get; set; }
        public string Name_Album { get; set; }
        public decimal Price { get; set; }
        public int Musician_ID { get; set; }
        public string Condition_ID_Cover { get; set; }
        public string Condition_ID_Vinyl { get; set; }
        public int Genre_ID { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Condition Condition1 { get; set; }
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Info_Products> Info_Products { get; set; }
        public virtual Musicians Musicians { get; set; }
    }
}
