//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneporject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID_Employee { get; set; }
        public string Surname_Employee { get; set; }
        public string Name_Employee { get; set; }
        public string Patronymic_Employee { get; set; }
        public int Director_ID { get; set; }
    
        public virtual Directors Directors { get; set; }
    }
}
